{% set name = "behave-html-pretty-formatter" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/behave_html_pretty_formatter-{{ version }}.tar.gz
  sha256: fae5a96613f61046510c6418accd06dbcd212b698cc28042039dc3ee5d2c0a5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=59
    - pip
  run:
    - python >={{ python_min }}
    - behave
    - dominate ==2.9.0
    - markdown

test:
  imports:
    - behave_html_pretty_formatter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Pretty HTML Formatter for Behave
  home: https://github.com/behave-contrib/behave-html-pretty-formatter
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
