schema_version: 1

context:
  name: behave-html-pretty-formatter
  version: 1.15.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/behave_html_pretty_formatter-${{ version }}.tar.gz
  sha256: dd260e7914d679f14004b5e44623c1bd8fb440fbbf6d07e96566d2ce1b168f37

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=59
    - pip
  run:
    - pyhamcrest
    - python >=${{ python_min }}
    - behave >=1.3.0
    - dominate ==2.9.0
    - markdown

tests:
  - python:
      imports:
        - behave_html_pretty_formatter
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Pretty HTML Formatter for Behave
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/behave-contrib/behave-html-pretty-formatter

extra:
  recipe-maintainers:
    - rxm7706
